networks:
  service:
    driver: bridge

services:
  backend:
    build:
      context: ../..
      dockerfile: .deploy/local/Dockerfile
    networks:
      - service
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: postgres:15-alpine3.17
    environment:
      POSTGRES_DB: ${DB_NAME:-postgres}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
    networks:
      - service